// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/_layout.tsx";
import * as $3 from "./routes/api/joke.ts";
import * as $4 from "./routes/greet/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/index2.tsx";
import * as $$0 from "./islands/interfaces/SignalStateDiagnosticOutPut.tsx";
import * as $$1 from "./islands/interfaces/SvgFractionTreeConfig.tsx";
import * as $$2 from "./islands/interfaces/SvgFractionTreePlot.tsx";
import * as $$3 from "./islands/templates/Counter2.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/_layout.tsx": $2,
    "./routes/api/joke.ts": $3,
    "./routes/greet/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/index2.tsx": $6,
  },
  islands: {
    "./islands/interfaces/SignalStateDiagnosticOutPut.tsx": $$0,
    "./islands/interfaces/SvgFractionTreeConfig.tsx": $$1,
    "./islands/interfaces/SvgFractionTreePlot.tsx": $$2,
    "./islands/templates/Counter2.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
